CourseWork2/Models/Account.cs
using EmploymentAgency.Models;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace CourseWork2.Models
{
    public class Account
    {
        public int Id { get; set; }
        public IdentityUser User { get; set; }
        public string Info { get; set; }
        public string PhoneNumber { get; set; }  
        public string Name { get; set; }
        public ICollection<Resume> Resumes { get; set; }
        public ICollection<EmployerRequest> EmployerRequests { get; set; }
    }
}

CourseWork2/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CourseWork2.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

CourseWork2/Controllers/ResumesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Core;
using Microsoft.EntityFrameworkCore;
using CourseWork2.Data;
using EmploymentAgency.Models;
using Microsoft.AspNetCore.Identity;
using CourseWork2.Models;
using NuGet.Versioning;
using Microsoft.AspNetCore.Authorization;
using NUnit.Framework;
using NLog;
using X.PagedList;

namespace CourseWork2.Controllers
{
    public class ResumesController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<IdentityUser> _userManager;

        private readonly ILogger<ResumesController> _logger;

        public ResumesController(ApplicationDbContext context, UserManager<IdentityUser> userManager, ILogger<ResumesController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }
        //Отклик на резюме
        [Authorize]
        public async Task<IActionResult> Respond(int? id)
        {
            IdentityUser identityUser = _userManager.GetUserAsync(HttpContext.User).Result;
            Account account = new Account();
            account = await _context.Accounts
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.User == identityUser);
            if (id == null || _context.Resumes == null)
            {
                return NotFound();
            }

            var resume = await _context.Resumes.Include(a => a.Responds).FirstOrDefaultAsync(m => m.Id == id);
            if (resume == null)
            {
                return NotFound();
            }
            resume.Responds.Add(account);
            _context.Update(resume);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //Публикация резюме модератором
        [Authorize(Roles = "MODERATOR")]
        public async Task<IActionResult> Publish(int? id)
        {
            if (id == null || _context.Resumes == null)
            {
                return NotFound();
            }

            var resume = await _context.Resumes.FindAsync(id);
            if (resume == null)
            {
                return NotFound();
            }
            resume.Status = _context.Statuses.Find(2);
            _context.Update(resume);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();
        // GET: Resumes
        [Authorize]
        public async Task<IActionResult> Index(int Id, int? pageNumber, string? searchText)
        {
            const int pageSize = 3;
            int pageCount;

            IdentityUser identityUser = _userManager.GetUserAsync(HttpContext.User).Result;
            Account userAccount = _context.Accounts.FirstOrDefault(u => u.User.Id == identityUser.Id);
            Task<IPagedList<Resume>> applicationDbContext;

            if (User.IsInRole("MODERATOR"))
            {
                applicationDbContext = _context.Resumes
                    .Include(e => e.Education)
                    .Include(e => e.Status)
                    .Include(e => e.User)
                    .Include(e => e.Responds)
                        .ThenInclude(u => u.User)
                    .ToPagedListAsync(pageNumber ?? 1, pageSize);

                pageCount = (int)Math.Ceiling(_context.Resumes.Count() / (float)pageSize);

                ViewData["pageCount"] = pageCount;
                return View(await applicationDbContext);
            }
            else
            {
                if (Id == 1)
                {
                    //Для соискателя
                    //Фильтр по текущему пользователю "Мои резюме"
                    if (searchText != null)
                    {
                        //Фильтр поиска по части названия
                        applicationDbContext = _context.Resumes
                        .Include(e => e.Education)
                        .Include(e => e.Status)
                        .Include(e => e.User)
                        .Include(e => e.Responds)
                            .ThenInclude(u => u.User)
                        .Where(e => (e.UserId == identityUser.Id) && (e.Post.Contains(searchText)))
                        .ToPagedListAsync(pageNumber ?? 1, pageSize);
                        pageCount = (int)Math.Ceiling(_context.Resumes.Where(e => e.UserId == identityUser.Id && (e.Post.Contains(searchText))).Count() / (float)pageSize);
                    }
                    else
                    {
                        //Без фильтра поиска по части названия
                        applicationDbContext = _context.Resumes
                            .Include(e => e.Education)
                            .Include(e => e.Status)
                            .Include(e => e.User)
                            .Include(e => e.Responds)
                                .ThenInclude(u => u.User)
                            .Where(e => e.UserId == identityUser.Id)
                            .ToPagedListAsync(pageNumber ?? 1, pageSize);
                        pageCount = (int)Math.Ceiling(_context.Resumes.Where(e => e.UserId == identityUser.Id).Count() / (float)pageSize);
                    }
                    ViewData["filteredValues"] = Id;
                    ViewData["pageCount"] = pageCount;
                    return View(await applicationDbContext);
                }
                else
                {
                    //Для работодателя
                    //Выборка всех значений со статусом "Опубликовано"
                    if (searchText != null)
                    {
                        //Фильтр поиска по части названия
                        applicationDbContext = _context.Resumes
                        .Include(e => e.Education)
                        .Include(e => e.Status)
                        .Include(e => e.User)
                        .Include(e => e.Responds)
                            .ThenInclude(u => u.User)
                        .Where(e => (e.StatusId == 2) && (e.Post.Contains(searchText)))
                        .ToPagedListAsync(pageNumber ?? 1, pageSize);
                        pageCount = (int)Math.Ceiling(_context.Resumes.Where(e => e.StatusId == 2 && (e.Post.Contains(searchText))).Count() / (float)pageSize);
                    }
                    else
                    {
                        //Без фильтра поиска по части названия
                        applicationDbContext = _context.Resumes
                            .Include(e => e.Education)
                            .Include(e => e.Status)
                            .Include(e => e.User)
                            .Include(e => e.Responds)
                                .ThenInclude(u => u.User)
                            .Where(e => e.StatusId == 2)
                            .ToPagedListAsync(pageNumber ?? 1, pageSize);
                        pageCount = (int)Math.Ceiling(_context.Resumes.Where(e => e.StatusId == 2).Count() / (float)pageSize);
                    }

                    if (userAccount == null)
                    {
                        _logger.LogInformation("Для того чтобы откликнуться на резюме, создайте аккаунт и перезайтие в свою учётную запись");
                        ViewBag.Message = "Для того чтобы откликнуться на резюме, создайте аккаунт и перезайтие в свою учётную запись";
                    }
                    ViewData["searchText"] = searchText;
                    ViewData["pageCount"] = pageCount;
                    return View(await applicationDbContext);
                }
            }
        }

        // GET: Resumes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Resumes == null)
            {
                return NotFound();
            }

            var resume = await _context.Resumes
                .Include(e => e.Education)
                .Include(e => e.Status)
                .Include(e => e.User)
                .Include(e => e.Responds)
                    .ThenInclude(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }
        // GET: Resumes/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["EducationId"] = new SelectList(_context.Educations, "Id", "Name");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName");
            return View();
        }

        // POST: Resumes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,DateCreated,Post,Info,EducationId,Salary,StatusId")] Resume resume)
        {
            IdentityUser identityUser = _userManager.GetUserAsync(HttpContext.User).Result;
            resume.DateCreated = DateTime.Now;
            resume.Status = _context.Statuses.Find(1);
            resume.User = _userManager.GetUserAsync(HttpContext.User).Result;
            resume.Education = _context.Educations.Find(resume.EducationId);
            _context.Add(resume);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = 1 });

CourseWork2/Views/Accounts/AccountPreview.cshtml
@model IEnumerable<CourseWork2.Models.Account>

@{
    ViewData["Title"] = "Index";
}

<h1>Профиль</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Просмотр профиля соискателя
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <h2>Имя</h2>
                    @Html.DisplayFor(modelItem => item.User.UserName)
                    
                    <h2>E-mail</h2>
                    @Html.DisplayFor(modelItem => item.User.Email)

                    <h2>Номер телефона</h2>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    <h2>Информация</h2>
                    @Html.DisplayFor(modelItem => item.Info)
                
                </td>
            </tr>
        }
    </tbody>
</table>

CourseWork2/Views/Accounts/Create.cshtml
@model CourseWork2.Models.Account

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Account</h4>
<h3 style="color: red;">После создания аккаунта вам необходимо повторить вход в аккаунт</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseWork2/Views/Accounts/Delete.cshtml
@model CourseWork2.Models.Account

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CourseWork2/Views/Accounts/Details.cshtml
@model CourseWork2.Models.Account

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CourseWork2/Views/Accounts/Edit.cshtml
@model CourseWork2.Models.Account

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseWork2/Views/Accounts/Index.cshtml
@model IEnumerable<CourseWork2.Models.Account>
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Мой аккаунт";
}

<table class="table">
    <thead>
        <tr>
            <th>
                Профиль
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    <h2>Имя</h2>
                    @Html.DisplayFor(modelItem => item.User.UserName)
                </td>
                <td>
                    <h2>Информация</h2>
                    @Html.DisplayFor(modelItem => item.Info)
                </td>
                <td>
                    <h2>E-mail</h2>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td>
                    <h2>Номер телефона</h2>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
            <td>
                @*@inject UserManager<IdentityUser> UserManager
                @{
                    var currentUser = await UserManager.GetUserAsync(User);
                    var currentUserId = currentUser.Id;
                }
                @if (item.User.Id == currentUserId)
                {*@
                    <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                    <a asp-action="Details" asp-route-id="@item.Id">Детали</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
               @* }*@
            </td>
        </tr>
        <tr>
            <td>
                <h2>Избранные Резюме</h2>
                @foreach (var resume in item.Resumes)
                {
                    <p>
                        <a asp-controller="Resumes" asp-action="Details" asp-route-id="@resume.Id">@resume.Post</a>
                    </p>
                }
            </td>
            <td>
                <h2>Избранные вакансии</h2>
                @foreach (var employerRequest in item.EmployerRequests)
                {
                    <p>
                        <a asp-controller="EmployerRequests" asp-action="Details" asp-route-id="@employerRequest.Id">@employerRequest.Post</a>
                    </p>
                }
            </td>
        </tr>
}
    </tbody>
</table>